Story Details base
WeDevelop-ARG/wedevelop-site pull request #232
Opened 2021-10-27 14:45 UTC by hjgonzalez06

2021-11-09 17:31 UTC, nahudalla requested changes
Lo arreglo yo en breve.

2021-11-09 17:31 UTC, nahudalla commented on src/portfolio/story_details/index.js
> +      />
Falta la URL de la página de contacto.

2021-11-09 17:55 UTC, hjgonzalez06 commented on src/portfolio/story_details/index.js
> +      />
Se la agregué en el PR 240

2021-11-10 18:47 UTC, nahudalla approved these changes

2021-11-10 18:47 UTC, merged