Story Details' Header section
WeDevelop-ARG/wedevelop-site pull request #235
Opened 2021-10-28 18:54 UTC by hjgonzalez06

2021-11-04 15:59 UTC, hjgonzalez06 commented
No hacer merge hasta que modifique algunas cosas en relación a los PRs 232 y 233 (después que estos estén mergeados).

2021-11-09 17:42 UTC, nahudalla reviewed
Lo voy a estar arreglando en breve.

2021-11-09 17:42 UTC, nahudalla commented on src/portfolio/story_details/components/Header/index.js
> +              alt='LOGO'
Usar un valor apropiado.

2021-11-09 17:42 UTC, nahudalla commented on src/portfolio/story_details/components/Header/index.js
> +            <img src='' alt='' className={classes.worldIcon} />
`src` vacío?? 🤔

2021-11-09 17:42 UTC, nahudalla commented on src/portfolio/story_details/components/Header/index.js
> +          })}
```suggestion
          {tags.map((tag) => (
            <span
              key={tag}
              className={classes.tag}
            >
              {tag}
            </span>
          ))}
```

2021-11-09 17:43 UTC, nahudalla requested changes
Me equivoqué de opción.

2021-11-09 18:27 UTC, hjgonzalez06 commented on src/portfolio/story_details/components/Header/index.js
> +              alt='LOGO'
Por eso te comenté que tenía que esperar a mergear las ramas de vani, porque estas imágenes ya las tenía ella. Era para que dos PRs no tuviesen las mismas imágenes.

2021-11-09 18:28 UTC, hjgonzalez06 commented on src/portfolio/story_details/components/Header/index.js
> +            <img src='' alt='' className={classes.worldIcon} />
Por eso te comenté que tenía que esperar a mergear las ramas de vani, porque estas imágenes ya las tenía ella. Era para que dos PRs no tuviesen las mismas imágenes.

2021-11-10 21:50 UTC, nahudalla approved these changes

2021-11-10 21:52 UTC, merged